AY2324S1-CS2103T-T12-1/tp

docs/UserGuide.md

Update and remove ab3 in the UG

Update and remove ab3 in the user guide

---

README.md
docs/AboutUs.md
docs/_config.yml

Closes #39, closes #40, closes #41, closes #42, closes #43. This should allow the tP progress dashboard to update and complete.
I would like to request a sanity check on the files I have changed, especially the portfolio links in AboutUs.md, if they are indeed correctly done. Otherwise, this will be fine to merge.

V1.1 cleanup

---

src/test/java/seedu/address/model/AddressBookTest.java
src/test/java/seedu/address/model/UserPrefsTest.java
src/test/java/seedu/address/model/fields/CommentTest.java
src/test/java/seedu/address/model/person/AttendanceTest.java
src/test/java/seedu/address/model/person/EmailTest.java
src/test/java/seedu/address/model/person/NameTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/model/person/PhoneTest.java
src/test/java/seedu/address/model/person/UniquePersonListTest.java
src/test/java/seedu/address/model/tag/TagTest.java
src/test/java/seedu/address/model/util/SampleDataUtilTest.java

Increase test coverage of model to 100%.

Update Test Coverage

---

docs/team/proto-aiken-13.md
src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/MainWindow.fxml

Our application needs to have a unique and functional AI from the original AB3 design.
Let's finish the AI for good! Updated DarkTheme and MainWindow.fxml to show a more complete UI.

Amend the UI fxml and css files to create a more complete UI.

---

src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml

Closes https://github.com/AY2324S1-CS2103T-T12-1/tp/issues/69.
This commit adds the ability to contact the student telegram at the click of a button to make it easier for TAs to navigate

Add telegram link

---

src/main/java/seedu/address/ui/PersonCard.java

Fix crashing bug in Linux

---

src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/PersonListCard.fxml

Add tag colours and distinguish the different types of information

---

src/main/java/seedu/address/storage/JsonAdaptedPerson.java

Fixed bug where comments and assignments are forgotten upon closing

---

docs/UserGuide.md
docs/team/choonyan02.md
src/main/java/seedu/address/logic/commands/ListParticipationCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ListParticipationParser.java
src/main/java/seedu/address/model/person/Attendance.java
src/test/java/seedu/address/logic/commands/ListParticipationCommandTest.java
src/test/java/seedu/address/logic/parser/ListParticipationParserTest.java

This pull request introduces the "ListParticipationCommand," a new feature designed for Teaching Assistants (TAs). The command enables TAs to view and assess students' attendance and participation points easily. 
This feature addresses the need for TAs to have an efficient and comprehensive tool to monitor student attendance and participation.

Add listParticipation command

---

docs/team/et-irl.md
src/main/resources/view/DarkTheme.css
src/main/resources/view/PersonListCard.fxml

The UI is quite small. This PR increases the font size of the UI, and splits off the information into the academic info on the first line, and the contact information on the second, to make it less cramped. We also add headers in front of the tags, comments and assignments for clarity.
Closes #79.

UI changes

---

docs/UserGuide.md
docs/team/lsyurea.md
src/main/java/seedu/address/logic/commands/UnmarkGroupAttendanceCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/UnmarkGroupAttendanceParser.java
src/main/java/seedu/address/model/person/Attendance.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/PersonListCard.fxml

This pull request addresses the need to unmark attendance for students in the current group.
This change is essential to improve the attendance tracking feature in our application. It allows students in the current group to have their attendance status reset when needed. This ensures that accurate attendance records are maintained.
Please review the following items:
Please review this pull request thoroughly and provide your feedback and approval for merging. Thank you.

Unmark group branch

---

docs/UserGuide.md
docs/_layouts/default.html

Reformat User Guide
Reformat User Guide

Reformat User Guide

---

src/main/java/seedu/address/logic/commands/GradeCommand.java
src/main/java/seedu/address/logic/commands/GradeGroupCommand.java
src/main/java/seedu/address/logic/commands/InputParticipationCommand.java
src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
src/main/java/seedu/address/logic/commands/MarkGroupAttendanceCommand.java
src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
src/main/java/seedu/address/logic/commands/UnmarkGroupAttendanceCommand.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/UniquePersonList.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java

Simplified some commands to reduce the code complexity.

Simplified some commands

---

docs/UserGuide.md
src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AssignmentCommand.java
src/main/java/seedu/address/logic/commands/AssignmentGroupCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/model/person/Email.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/Phone.java
src/main/java/seedu/address/model/person/TelegramHandle.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/ui/PersonCard.java
src/test/java/seedu/address/model/person/EmailTest.java
src/test/java/seedu/address/model/person/PhoneTest.java
src/test/java/seedu/address/model/person/TelegramHandleTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/PersonUtil.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Change logic for default. Initially it was set to default, now I add it such that they can put nothing and it becomes a dash
Change logic for default. Initially it was set to default, now I add it such that they can put nothing and it becomes a dash

Change logic for default

---

docs/UserGuide.md
docs/team/choonyan02.md
src/main/java/seedu/address/logic/commands/InputGroupParticipationCommand.java
src/main/java/seedu/address/logic/commands/InputParticipationCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/InputGroupParticipationParser.java
src/test/java/seedu/address/logic/commands/InputGroupParticipationCommandTest.java
src/test/java/seedu/address/logic/parser/InputGroupParticipationParserTest.java

Add inputGroupPP command
Allows the user to input the same participation points to all the students at one go

Add inputGroupPP command

---

docs/UserGuide.md
docs/tutorials/RemovingFields.md
src/main/java/seedu/address/model/person/TelegramHandle.java
src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/model/person/TelegramHandleTest.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Telegram handle cannot end with an underscore and must start with a letter fixed with updated UG parameter
Closes #146 

Update regex for telegram

---

src/main/java/seedu/address/model/person/Attendance.java

When we unmark attendance, the participation points given should be changed to 0 too.

Slight logic changes to Attendance

---

src/main/resources/view/DarkTheme.css
src/main/resources/view/PersonListCard.fxml

Fix emoticon

---

src/main/java/seedu/address/logic/parser/AddressBookParser.java

As it is, the implementation is not very OOP friendly and extensible. We rely on a hardcoded boolean variable specific to only 1 command.
We should instead be tracking the last command entered, and use `instanceof` to easily extend such confirmation features.
When we type `clear`, and then `yes`, we can generalise this behaviour for other functions too.

Make previous command tracking more extensible

---

docs/UserGuide.md

Some `<br>` tags were missing in the user guide, causing it to render incorrectly.

Fix minor error in User Guide

---

docs/DeveloperGuide.md
docs/diagrams/InputParticipationActivityDiagram.puml
docs/diagrams/MarkAttendanceActivityDiagram.puml

Updated developer documentation to have PUML classes for the attendance classes as well as the Developer Guide to include use cases for the updated attendance marking classes.
Added activity diagrams for marking attendance and indicating participation.
Added activity diagrams for marking attendance and indicating participation for the DG requirements.

Update developer documentation

---

docs/UserGuide.md

It is not explained what the smiley faces, xes, and `:/` (what is this face) mean in the UI, which confused some testers. We add this to the glossary.
Closes #205.

Add status to glossary

---

docs/UserGuide.md

Refer to the issue it closes.
Closes #199.

Fix documentation for `findGroup`

---

docs/UserGuide.md

Remove duplicate entries in the common parameters section
Closes #198

Fix duplicate entries in the common parameters section

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
src/main/java/seedu/address/logic/commands/MarkGroupAttendanceCommand.java
src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
src/main/java/seedu/address/logic/commands/UnmarkGroupAttendanceCommand.java

Fixes the documentation for the summary. Check the diff for details, self-explanatory.
Closes #201.

Fix documentation for missing status fields in attendance commands

---

docs/DeveloperGuide.md

Self-explanatory; check issue.
Closes #220

Fix numbering

---

docs/UserGuide.md

"Check out the user guide here!" does not have any hyperlink on _here_.
Closes #225

Add missing hyperlink

---

src/main/java/seedu/address/ui/UiUtil.java

Self-explanatory.
Closes #190.

Relink User Guide URL

---

src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/AssignmentCommandParser.java
src/main/java/seedu/address/logic/parser/AssignmentGroupCommandParser.java
src/main/java/seedu/address/logic/parser/AssignmentIndivCommandParser.java
src/main/java/seedu/address/logic/parser/DeassignmentCommandParser.java
src/main/java/seedu/address/logic/parser/DeassignmentIndivCommandParser.java
src/main/java/seedu/address/logic/parser/InputGroupParticipationParser.java
src/main/java/seedu/address/logic/parser/InputParticipationParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java

There is too much code reduplication of the above function. We place it where it should be.
Closes #186 

Refactor `arePrefixesPresent` into `ParserUtil`

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/AssignmentGroupCommand.java

Fix grammar and stylisation issues.

---

docs/UserGuide.md

Closes #212 
Updated the user guide to the current version

Fix GUI user guide

---

src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/model/person/Group.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java

Fix group command message Closes #210 

Fix group command

---

docs/UserGuide.md

Fix grade command User Guide Closes #214 
Fix grade command User Guide to include 0 and max score boundary (inclusive)

Fix grade command User Guide

---

docs/UserGuide.md

Refactor User Guide to be more uniform
Refactor User Guide to be more uniform

Refactor User Guide to be more uniform

---

docs/DeveloperGuide.md

Add a demo for the application thus far.
Added a demo to meet the weekly deliverables.
Closes #244

Branch demo

---

docs/team/proto-aiken-13.md
src/main/java/seedu/address/logic/parser/MarkAttendanceParser.java
src/test/java/seedu/address/logic/parser/MarkAttendanceParserTest.java

Amended the error message in MarkAttendanceParser in the case that the markAtd command inputted has missing parameters. Also, updated my documentation of contribution to be more consistent with the rest of the team with my contributions to the project thus far.
Bug fix based on the issue raised by one of the testers, in which no command format error was not thrown for incorrect format of the markAtd command.
Closes #200 

Amend error detection behaviour in MarkAttendanceParser

---

docs/UserGuide.md
docs/team/vanessamae23.md
src/test/java/seedu/address/model/person/AssignmentTest.java

Closes #217 #213 
Stated in the user guide clearly that assigning the same assignment will overwrite since this is the intended design
Stated the assignment sensitivity

Add assignment test and update UG to state case sensitivity of Assignment

---

build.gradle
docs/tutorials/AddRemark.md
src/main/java/seedu/address/model/UserPrefs.java
src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java

Change filename from addressbook to npctrack
Closes #191 
Changed the json and jar files

Change filename from addressbook to npctrack

---

docs/UserGuide.md

Fix Table user guide

---

docs/UserGuide.md

The user guide is pretty much already done for Windows. We just add that it can be done with Mac and Linux too.
Closes #218. Closes #247.

Add Mac and Linux to guide

---

docs/UserGuide.md

We specify the constraints of grade group properly in the user guide.
Closes #219.

Add clarification to gradeGroup command

---

docs/UserGuide.md

Specify that groups are case-sensitive.
Closes #208.

Specify that groups are case-sensitive

---

docs/UserGuide.md

Add in the guide that score graded to a group must be less than all assignments.
Closes #216.

Add clarification of maximum score

---

docs/_sass/minima/_base.scss

Previosuly it was AB-3 now changed to NPC_TRACK

Change header for the documents

---

src/main/java/seedu/address/logic/commands/AssignmentGroupCommand.java
src/test/java/seedu/address/logic/commands/AssignmentCommandTest.java
src/test/java/seedu/address/logic/commands/AssignmentGroupCommandTest.java

Create test cases for assignment and group assignment

Create assignment and group assignment test

---

docs/UserGuide.md

Closes #286 
There is a missing link that reduces consistency for the user guide . Closes #286 

Fix missing link

---

docs/UserGuide.md

The grammar pains me on a spiritual level so I have made changes to the User Guide

Make wording changes to the User Guide

---

docs/DeveloperGuide.md
docs/UserGuide.md
docs/team/choonyan02.md

Fix some mistakes

---

docs/DeveloperGuide.md

Fix mistake in #290

---

docs/DeveloperGuide.md
docs/UserGuide.md

Fix UG and DG

---

docs/DeveloperGuide.md
docs/UserGuide.md

Removed Extraneous Space
Removed Extraneous Space

Removed Extraneous Space
